# Generated by Django 2.2.10 on 2020-04-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif_usr', '0004_remove_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doc_url',
            field=models.CharField(default='', max_length=30),
        ),
    ]
