# Generated by Django 3.0.2 on 2020-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif_usr', '0005_user_doc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='short_story',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
