# Generated by Django 3.0.2 on 2020-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif_usr', '0006_auto_20200417_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='short_story',
            field=models.TextField(default=''),
        ),
    ]
