# Generated by Django 3.0.2 on 2020-04-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verif_usr', '0008_auto_20200417_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
